name = "trendpulse-backend"
main = "src/index.ts"
compatibility_date = "2024-03-06"

[[d1_databases]]
binding = "DB"
database_name = "trendpulse-db"
database_id = "31ffd993-310f-4bd6-a44c-cfcac4bf4a90"

[triggers]
crons = ["0 * * * *"] # Every hour

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "trendpulse-vectors"
